# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/junaid29707/Desktop/202401102/Hacktoberfest/new/NewNew/Hacktoberfest2k25_cpp_MemoryCardFlipGame

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/junaid29707/Desktop/202401102/Hacktoberfest/new/NewNew/Hacktoberfest2k25_cpp_MemoryCardFlipGame/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/junaid29707/Desktop/202401102/Hacktoberfest/new/NewNew/Hacktoberfest2k25_cpp_MemoryCardFlipGame/build/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/junaid29707/Desktop/202401102/Hacktoberfest/new/NewNew/Hacktoberfest2k25_cpp_MemoryCardFlipGame/build/CMakeFiles /home/junaid29707/Desktop/202401102/Hacktoberfest/new/NewNew/Hacktoberfest2k25_cpp_MemoryCardFlipGame/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/junaid29707/Desktop/202401102/Hacktoberfest/new/NewNew/Hacktoberfest2k25_cpp_MemoryCardFlipGame/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named memory_card_game

# Build rule for target.
memory_card_game: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 memory_card_game
.PHONY : memory_card_game

# fast build rule for target.
memory_card_game/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game.dir/build.make CMakeFiles/memory_card_game.dir/build
.PHONY : memory_card_game/fast

#=============================================================================
# Target rules for targets named memory_card_game_tests

# Build rule for target.
memory_card_game_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 memory_card_game_tests
.PHONY : memory_card_game_tests

# fast build rule for target.
memory_card_game_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game_tests.dir/build.make CMakeFiles/memory_card_game_tests.dir/build
.PHONY : memory_card_game_tests/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f _deps/raylib-build/CMakeFiles/uninstall.dir/build.make _deps/raylib-build/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named raylib

# Build rule for target.
raylib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 raylib
.PHONY : raylib

# fast build rule for target.
raylib/fast:
	$(MAKE) $(MAKESILENT) -f _deps/raylib-build/raylib/CMakeFiles/raylib.dir/build.make _deps/raylib-build/raylib/CMakeFiles/raylib.dir/build
.PHONY : raylib/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f _deps/raylib-build/raylib/external/glfw/src/CMakeFiles/glfw.dir/build.make _deps/raylib-build/raylib/external/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f _deps/raylib-build/raylib/external/glfw/src/CMakeFiles/update_mappings.dir/build.make _deps/raylib-build/raylib/external/glfw/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

src/AudioManager.o: src/AudioManager.cpp.o
.PHONY : src/AudioManager.o

# target to build an object file
src/AudioManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game.dir/build.make CMakeFiles/memory_card_game.dir/src/AudioManager.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game_tests.dir/build.make CMakeFiles/memory_card_game_tests.dir/src/AudioManager.cpp.o
.PHONY : src/AudioManager.cpp.o

src/AudioManager.i: src/AudioManager.cpp.i
.PHONY : src/AudioManager.i

# target to preprocess a source file
src/AudioManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game.dir/build.make CMakeFiles/memory_card_game.dir/src/AudioManager.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game_tests.dir/build.make CMakeFiles/memory_card_game_tests.dir/src/AudioManager.cpp.i
.PHONY : src/AudioManager.cpp.i

src/AudioManager.s: src/AudioManager.cpp.s
.PHONY : src/AudioManager.s

# target to generate assembly for a file
src/AudioManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game.dir/build.make CMakeFiles/memory_card_game.dir/src/AudioManager.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game_tests.dir/build.make CMakeFiles/memory_card_game_tests.dir/src/AudioManager.cpp.s
.PHONY : src/AudioManager.cpp.s

src/Card.o: src/Card.cpp.o
.PHONY : src/Card.o

# target to build an object file
src/Card.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game.dir/build.make CMakeFiles/memory_card_game.dir/src/Card.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game_tests.dir/build.make CMakeFiles/memory_card_game_tests.dir/src/Card.cpp.o
.PHONY : src/Card.cpp.o

src/Card.i: src/Card.cpp.i
.PHONY : src/Card.i

# target to preprocess a source file
src/Card.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game.dir/build.make CMakeFiles/memory_card_game.dir/src/Card.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game_tests.dir/build.make CMakeFiles/memory_card_game_tests.dir/src/Card.cpp.i
.PHONY : src/Card.cpp.i

src/Card.s: src/Card.cpp.s
.PHONY : src/Card.s

# target to generate assembly for a file
src/Card.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game.dir/build.make CMakeFiles/memory_card_game.dir/src/Card.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game_tests.dir/build.make CMakeFiles/memory_card_game_tests.dir/src/Card.cpp.s
.PHONY : src/Card.cpp.s

src/Game.o: src/Game.cpp.o
.PHONY : src/Game.o

# target to build an object file
src/Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game.dir/build.make CMakeFiles/memory_card_game.dir/src/Game.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game_tests.dir/build.make CMakeFiles/memory_card_game_tests.dir/src/Game.cpp.o
.PHONY : src/Game.cpp.o

src/Game.i: src/Game.cpp.i
.PHONY : src/Game.i

# target to preprocess a source file
src/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game.dir/build.make CMakeFiles/memory_card_game.dir/src/Game.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game_tests.dir/build.make CMakeFiles/memory_card_game_tests.dir/src/Game.cpp.i
.PHONY : src/Game.cpp.i

src/Game.s: src/Game.cpp.s
.PHONY : src/Game.s

# target to generate assembly for a file
src/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game.dir/build.make CMakeFiles/memory_card_game.dir/src/Game.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game_tests.dir/build.make CMakeFiles/memory_card_game_tests.dir/src/Game.cpp.s
.PHONY : src/Game.cpp.s

src/GameBoard.o: src/GameBoard.cpp.o
.PHONY : src/GameBoard.o

# target to build an object file
src/GameBoard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game.dir/build.make CMakeFiles/memory_card_game.dir/src/GameBoard.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game_tests.dir/build.make CMakeFiles/memory_card_game_tests.dir/src/GameBoard.cpp.o
.PHONY : src/GameBoard.cpp.o

src/GameBoard.i: src/GameBoard.cpp.i
.PHONY : src/GameBoard.i

# target to preprocess a source file
src/GameBoard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game.dir/build.make CMakeFiles/memory_card_game.dir/src/GameBoard.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game_tests.dir/build.make CMakeFiles/memory_card_game_tests.dir/src/GameBoard.cpp.i
.PHONY : src/GameBoard.cpp.i

src/GameBoard.s: src/GameBoard.cpp.s
.PHONY : src/GameBoard.s

# target to generate assembly for a file
src/GameBoard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game.dir/build.make CMakeFiles/memory_card_game.dir/src/GameBoard.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game_tests.dir/build.make CMakeFiles/memory_card_game_tests.dir/src/GameBoard.cpp.s
.PHONY : src/GameBoard.cpp.s

src/ScoreManager.o: src/ScoreManager.cpp.o
.PHONY : src/ScoreManager.o

# target to build an object file
src/ScoreManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game.dir/build.make CMakeFiles/memory_card_game.dir/src/ScoreManager.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game_tests.dir/build.make CMakeFiles/memory_card_game_tests.dir/src/ScoreManager.cpp.o
.PHONY : src/ScoreManager.cpp.o

src/ScoreManager.i: src/ScoreManager.cpp.i
.PHONY : src/ScoreManager.i

# target to preprocess a source file
src/ScoreManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game.dir/build.make CMakeFiles/memory_card_game.dir/src/ScoreManager.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game_tests.dir/build.make CMakeFiles/memory_card_game_tests.dir/src/ScoreManager.cpp.i
.PHONY : src/ScoreManager.cpp.i

src/ScoreManager.s: src/ScoreManager.cpp.s
.PHONY : src/ScoreManager.s

# target to generate assembly for a file
src/ScoreManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game.dir/build.make CMakeFiles/memory_card_game.dir/src/ScoreManager.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game_tests.dir/build.make CMakeFiles/memory_card_game_tests.dir/src/ScoreManager.cpp.s
.PHONY : src/ScoreManager.cpp.s

src/Utils.o: src/Utils.cpp.o
.PHONY : src/Utils.o

# target to build an object file
src/Utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game.dir/build.make CMakeFiles/memory_card_game.dir/src/Utils.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game_tests.dir/build.make CMakeFiles/memory_card_game_tests.dir/src/Utils.cpp.o
.PHONY : src/Utils.cpp.o

src/Utils.i: src/Utils.cpp.i
.PHONY : src/Utils.i

# target to preprocess a source file
src/Utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game.dir/build.make CMakeFiles/memory_card_game.dir/src/Utils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game_tests.dir/build.make CMakeFiles/memory_card_game_tests.dir/src/Utils.cpp.i
.PHONY : src/Utils.cpp.i

src/Utils.s: src/Utils.cpp.s
.PHONY : src/Utils.s

# target to generate assembly for a file
src/Utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game.dir/build.make CMakeFiles/memory_card_game.dir/src/Utils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game_tests.dir/build.make CMakeFiles/memory_card_game_tests.dir/src/Utils.cpp.s
.PHONY : src/Utils.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game.dir/build.make CMakeFiles/memory_card_game.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game.dir/build.make CMakeFiles/memory_card_game.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game.dir/build.make CMakeFiles/memory_card_game.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

tests/test_card.o: tests/test_card.cpp.o
.PHONY : tests/test_card.o

# target to build an object file
tests/test_card.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game_tests.dir/build.make CMakeFiles/memory_card_game_tests.dir/tests/test_card.cpp.o
.PHONY : tests/test_card.cpp.o

tests/test_card.i: tests/test_card.cpp.i
.PHONY : tests/test_card.i

# target to preprocess a source file
tests/test_card.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game_tests.dir/build.make CMakeFiles/memory_card_game_tests.dir/tests/test_card.cpp.i
.PHONY : tests/test_card.cpp.i

tests/test_card.s: tests/test_card.cpp.s
.PHONY : tests/test_card.s

# target to generate assembly for a file
tests/test_card.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game_tests.dir/build.make CMakeFiles/memory_card_game_tests.dir/tests/test_card.cpp.s
.PHONY : tests/test_card.cpp.s

tests/test_gameboard.o: tests/test_gameboard.cpp.o
.PHONY : tests/test_gameboard.o

# target to build an object file
tests/test_gameboard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game_tests.dir/build.make CMakeFiles/memory_card_game_tests.dir/tests/test_gameboard.cpp.o
.PHONY : tests/test_gameboard.cpp.o

tests/test_gameboard.i: tests/test_gameboard.cpp.i
.PHONY : tests/test_gameboard.i

# target to preprocess a source file
tests/test_gameboard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game_tests.dir/build.make CMakeFiles/memory_card_game_tests.dir/tests/test_gameboard.cpp.i
.PHONY : tests/test_gameboard.cpp.i

tests/test_gameboard.s: tests/test_gameboard.cpp.s
.PHONY : tests/test_gameboard.s

# target to generate assembly for a file
tests/test_gameboard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game_tests.dir/build.make CMakeFiles/memory_card_game_tests.dir/tests/test_gameboard.cpp.s
.PHONY : tests/test_gameboard.cpp.s

tests/test_main.o: tests/test_main.cpp.o
.PHONY : tests/test_main.o

# target to build an object file
tests/test_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game_tests.dir/build.make CMakeFiles/memory_card_game_tests.dir/tests/test_main.cpp.o
.PHONY : tests/test_main.cpp.o

tests/test_main.i: tests/test_main.cpp.i
.PHONY : tests/test_main.i

# target to preprocess a source file
tests/test_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game_tests.dir/build.make CMakeFiles/memory_card_game_tests.dir/tests/test_main.cpp.i
.PHONY : tests/test_main.cpp.i

tests/test_main.s: tests/test_main.cpp.s
.PHONY : tests/test_main.s

# target to generate assembly for a file
tests/test_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game_tests.dir/build.make CMakeFiles/memory_card_game_tests.dir/tests/test_main.cpp.s
.PHONY : tests/test_main.cpp.s

tests/test_utils.o: tests/test_utils.cpp.o
.PHONY : tests/test_utils.o

# target to build an object file
tests/test_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game_tests.dir/build.make CMakeFiles/memory_card_game_tests.dir/tests/test_utils.cpp.o
.PHONY : tests/test_utils.cpp.o

tests/test_utils.i: tests/test_utils.cpp.i
.PHONY : tests/test_utils.i

# target to preprocess a source file
tests/test_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game_tests.dir/build.make CMakeFiles/memory_card_game_tests.dir/tests/test_utils.cpp.i
.PHONY : tests/test_utils.cpp.i

tests/test_utils.s: tests/test_utils.cpp.s
.PHONY : tests/test_utils.s

# target to generate assembly for a file
tests/test_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memory_card_game_tests.dir/build.make CMakeFiles/memory_card_game_tests.dir/tests/test_utils.cpp.s
.PHONY : tests/test_utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... uninstall"
	@echo "... update_mappings"
	@echo "... glfw"
	@echo "... memory_card_game"
	@echo "... memory_card_game_tests"
	@echo "... raylib"
	@echo "... src/AudioManager.o"
	@echo "... src/AudioManager.i"
	@echo "... src/AudioManager.s"
	@echo "... src/Card.o"
	@echo "... src/Card.i"
	@echo "... src/Card.s"
	@echo "... src/Game.o"
	@echo "... src/Game.i"
	@echo "... src/Game.s"
	@echo "... src/GameBoard.o"
	@echo "... src/GameBoard.i"
	@echo "... src/GameBoard.s"
	@echo "... src/ScoreManager.o"
	@echo "... src/ScoreManager.i"
	@echo "... src/ScoreManager.s"
	@echo "... src/Utils.o"
	@echo "... src/Utils.i"
	@echo "... src/Utils.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... tests/test_card.o"
	@echo "... tests/test_card.i"
	@echo "... tests/test_card.s"
	@echo "... tests/test_gameboard.o"
	@echo "... tests/test_gameboard.i"
	@echo "... tests/test_gameboard.s"
	@echo "... tests/test_main.o"
	@echo "... tests/test_main.i"
	@echo "... tests/test_main.s"
	@echo "... tests/test_utils.o"
	@echo "... tests/test_utils.i"
	@echo "... tests/test_utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

